CREATE DATABASE IF NOT EXISTS MyAdb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE  MyAdb;

GRANT ALL PRIVILEGES ON `MyAdb`.* TO 'MaSaRi'@'localhost'; 

CREATE USER 'MaSaRi'@'localhost' IDENTIFIED BY 'OOPss2017';

GRANT ALL PRIVILEGES ON *.* TO 'MaSaRi'@'localhost' IDENTIFIED BY 'OOPss2017' 
REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

