# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansprechpartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100, verbose_name='vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='nachname')),
                ('anrede', models.CharField(choices=[('K', 'Keine Auswahl'), ('F', 'Frau'), ('H', 'Herr')], default='K', max_length=1, verbose_name='anrede')),
                ('titel', models.CharField(max_length=100, null=True, verbose_name='titel')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('telefon', models.CharField(max_length=25, null=True, verbose_name='telefon')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='mobile')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=100, verbose_name='firma')),
                ('strasse', models.CharField(max_length=100, null=True, verbose_name='strasse')),
                ('plzort', models.CharField(max_length=100, null=True, verbose_name='plzort')),
                ('telefon', models.CharField(max_length=100, null=True, verbose_name='telefon')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('webseite', models.CharField(max_length=100, null=True, verbose_name='webseite')),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=75, verbose_name='nickname')),
                ('pwd', models.CharField(max_length=100, verbose_name='pwd')),
                ('vorname', models.CharField(max_length=100, verbose_name='vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='nachname')),
                ('anrede', models.CharField(choices=[('K', 'Keine Auswahl'), ('F', 'Frau'), ('H', 'Herr')], default='K', max_length=1, verbose_name='anrede')),
                ('titel', models.CharField(max_length=100, null=True, verbose_name='titel')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('telefon', models.CharField(max_length=25, null=True, verbose_name='telefon')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='mobile')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Notizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gespraechsart', models.IntegerField(default=0, verbose_name='gespraechsart')),
                ('notiztext', models.CharField(max_length=200, verbose_name='nituztext')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Ansprechpartner')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='TeilnehmerExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('ansprechpartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Ansprechpartner')),
            ],
        ),
        migrations.CreateModel(
            name='TeilnehmerInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiter', models.BooleanField(default=False, verbose_name='leiter')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='Termine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(default=datetime.datetime(2017, 6, 9, 15, 56, 13, 509454), verbose_name='datum')),
                ('titel', models.CharField(max_length=100, verbose_name='titel')),
                ('ort', models.CharField(max_length=100, verbose_name='ort')),
                ('ansprechpartner', models.ManyToManyField(through='MyA.TeilnehmerExt', to='MyA.Ansprechpartner')),
                ('mitarbeiter', models.ManyToManyField(through='MyA.TeilnehmerInt', to='MyA.Mitarbeiter')),
            ],
        ),
        migrations.AddField(
            model_name='teilnehmerint',
            name='termine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Termine'),
        ),
        migrations.AddField(
            model_name='teilnehmerext',
            name='termine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Termine'),
        ),
        migrations.AddField(
            model_name='ansprechpartner',
            name='kunden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Kunden'),
        ),
    ]
