# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('gender', models.CharField(blank=True, choices=[('N', 'Keine Auswahl'), ('F', 'Frau'), ('M', 'Herr')], default='N', max_length=1, verbose_name='gender')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Telefonnummern mit / oder -', regex='^[0-9 -\\/]+$')], verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Telefonnummern mit / oder -', regex='^[0-9 -\\/]+$')], verbose_name='fax')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='street')),
                ('plzcity', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='5 stellige PLZ und Stadt', regex='^\\d{5} [a-zA-ZäöüÄÖÜ -ß]+$')], verbose_name='plzcity')),
                ('phone', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Telefonnummern mit / oder -', regex='^[0-9 -\\/]+$')], verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Telefonnummern mit / oder -', regex='^[0-9 -\\/]+$')], verbose_name='fax')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='website')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('gender', models.CharField(blank=True, choices=[('N', 'Keine Auswahl'), ('F', 'Frau'), ('M', 'Herr')], default='N', max_length=1, verbose_name='salutation')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, verbose_name='fax')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='mobile')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='01.07.2017', verbose_name='date')),
                ('starttime', models.TimeField(verbose_name='starttime')),
                ('endtime', models.TimeField(verbose_name='endtime')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='MemberExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False, verbose_name='leader')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetext', models.CharField(max_length=1000, verbose_name='notetext')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 7, 1, 17, 28, 21, 330056), verbose_name='date')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Contact')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ManyToManyField(through='MyA.MemberExt', to='MyA.Contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ManyToManyField(through='MyA.MemberInt', to='MyA.Employee'),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Customer'),
        ),
    ]
