# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('gender', models.CharField(choices=[('N', 'No Select'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1, verbose_name='gender')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.CharField(max_length=25, null=True, verbose_name='phone')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='mobile')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='street')),
                ('plzcity', models.CharField(max_length=100, null=True, verbose_name='plzcity')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='phone')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('website', models.CharField(max_length=100, null=True, verbose_name='website')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 13, 14, 8, 51, 295528), verbose_name='date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='MemberExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Contacts')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Events')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False, verbose_name='leader')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calltype', models.IntegerField(default=0, verbose_name='calltype')),
                ('notetext', models.CharField(max_length=200, verbose_name='notetext')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=75, verbose_name='nickname')),
                ('pwd', models.CharField(max_length=100, verbose_name='pwd')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('gender', models.CharField(choices=[('N', 'No Select'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1, verbose_name='salutation')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('phone', models.CharField(max_length=25, null=True, verbose_name='phone')),
                ('fax', models.CharField(max_length=100, null=True, verbose_name='fax')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='mobile')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Staffs'),
        ),
        migrations.AddField(
            model_name='memberint',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Staffs'),
        ),
        migrations.AddField(
            model_name='events',
            name='contact',
            field=models.ManyToManyField(through='MyA.MemberExt', to='MyA.Contacts'),
        ),
        migrations.AddField(
            model_name='events',
            name='staff',
            field=models.ManyToManyField(through='MyA.MemberInt', to='MyA.Staffs'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyA.Customer'),
        ),
    ]
