# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', 'Keine Auswahl'), ('F', 'Frau'), ('M', 'Herr')], default='N', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', 'Keine Auswahl'), ('F', 'Frau'), ('M', 'Herr')], default='N', max_length=1, verbose_name='salutation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.EmailField(blank=True, max_length=100, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='01.07.2017', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.TimeField(verbose_name='endtime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.TimeField(verbose_name='starttime'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 23, 27, 11, 440896), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notetext',
            field=models.CharField(max_length=1000, verbose_name='notetext'),
        ),
    ]
